steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t southamerica-west1-docker.pkg.dev/projecto-microservicios/image-microservicios/orders-ms -f dockerfile.prod --platform=linux/amd64 --build-arg ORDERS_MS_DATABASE_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-west1-docker.pkg.dev/projecto-microservicios/image-microservicios/orders-ms',
      ]

availableSecrets:
  secretManager:
    - versionName: projects/691423266436/secrets/orders_database_url/versions/1
      env: 'DATABASE_URL'
